---
title: "Analyze_Fog_Data"
author: "Taro Katayama"
date: '2022-06-14'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
#install.packages('gganimate')
#install.packages('gifski')
library(gganimate)
library(gifski)
#install.packages('ggdark')
library(ggdark)
#install.packages("remotes")
#remotes::install_github("an-bui/calecopal")
library(calecopal)
```

```{r}
tarotheme<- dark_theme_bw()+theme(text = element_text(size = 11),
                                  panel.spacing = unit(0.5, 'lines'),
                                  strip.background = element_blank(),
                                  strip.text = element_text(size = 8, hjust = 0),
                                  strip.placement = 'outside',
                                  #panel.grid.minor = element_line(color= 'grey'),
                                  panel.grid.major = element_line(color = 'grey'))
```

```{r}

```


```{r}
#load in data, create master dataset
SB_Processed<- read.csv("./processed_data/SB/SB_processed_CR800.csv")
SB_Processed<- SB_Processed%>%
  mutate(Station="Spicy_Bunker")

TP_Processed<- read.csv("./processed_data/TP/TP_processed_CR800.csv")
TP_Processed<- TP_Processed%>%
  mutate(Station="Tide_Pool")

EB_Processed<- read.csv("./processed_data/EB/EB_processed_CR800.csv")
EB_Processed<- EB_Processed%>%
  mutate(Station="Event_Bluff")

NN_Processed<- read.csv("./processed_data/NN/NN_processed_CR800.csv")
NN_Processed<- NN_Processed%>%
  mutate(Station="New_New")

All_Sites<- rbind(SB_Processed, TP_Processed, EB_Processed, NN_Processed)

All_Sites$TIMESTAMP<- as.POSIXct(All_Sites$TIMESTAMP, 
                                    tz="", format = "%Y-%m-%d %H:%M")
All_Sites_Processed<- All_Sites%>%
  mutate(day=date(TIMESTAMP),
         hour=hour(TIMESTAMP))%>%
  filter(day>='2022-06-17'& day<='2022-06-28',)

```


```{r}
theday <- '2022-06-20'

All_Sites_Day<- All_Sites%>%
  mutate(day=date(TIMESTAMP))%>%
  filter(day==theday)
  
  All_Sites_Day$TIMESTAMP<- as.POSIXct(All_Sites_Day$TIMESTAMP, 
                                    tz="", format = "%Y-%m-%d %H:%M")
```


```{r}
LWS_All_Sites_Plot<- ggplot(All_Sites_Day, 
                            aes(x= TIMESTAMP, 
                                y= LWmV_66ft_Avg, 
                                color=Station)) +
  geom_line(size=01.5) +
  scale_x_datetime(breaks = "4 hours", date_labels = "%H:%M")+
  labs(x="June 20th", y="Leaf Wetness Sensor (mV)")+
  theme(legend.position = "bottom")+
  scale_color_manual(values = cal_palette(name="dudleya", n=4, 
                                          type = "continuous"))+
  tarotheme+
  theme(axis.text.x = element_text(angle = 90))

LWS_All_Sites_Plot

animateplot<- LWS_All_Sites_Plot+ transition_reveal(TIMESTAMP)
animate(animateplot, fps = 4)
anim_save('LWS_06_20.gif')


LWS_All_Sites_Plot
```

```{r}
ggplot(All_Sites_Processed,
       aes(x = TIMESTAMP, y = LWmV_66ft_Avg, color = Station))+
  geom_line(size=.4) +
  #facet_wrap(~day)+
  scale_y_continuous()+
  scale_x_datetime(breaks = "1 day")+
  scale_color_manual(values = cal_palette("chaparral2"))+
  tarotheme+
  theme(axis.text.x = element_text(angle = 90))

```


```{r}

Weather_Function <- function(dataset, the_day, xvar, yvar){

  dataset <- dataset %>%
  mutate(day=date(TIMESTAMP))%>%
  filter(day==the_day)

  ggplot(data = dataset, aes(x = get(xvar), y = get(yvar), color = Station))+
  geom_line()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90))
}

Weather_Function(All_Sites, '2022-06-27','TIMESTAMP', 'LWmV_66ft_Avg')

#different variables
'WindDir_D1_WVT'
'AirT_C_Avg'
'RH_Avg'
'LWmV_17ft_Avg'
'LWmV_50ft_Avg'
'LWmV_66ft_Avg'
'WS_ms_Avg'
```
