---
title: "Clean CR800 .dat data file"
author: "Taro Katayama & Brent Wilder"
date: '2022-06-10'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(dplyr)
library(lubridate)
#library(mapview)
#mapviewOptions(fgb = FALSE)
#library(sf)
library(knitr)
library(Kendall)
library(zoo)
library(gridExtra)
library(readr)
#install.packages("janitor")
library(janitor)
```

```{r}

getwd()
# Read to CSV 
data <- read.csv("./raw_data/SB/20220613_CR800Series_FogTable_SB.dat", skip = 1, stringsAsFactors = TRUE)
#Take out the first two rows
spicyraw6_13<- data[-c(1,2), ]
#set timestamp as date
str(spicyraw)
spicyraw6_13$TIMESTAMP<- as.POSIXct(spicyraw6_13$TIMESTAMP, tz="", format = "%Y-%m-%d %H:%M")

# Read to CSV 
data2 <- read.csv("./raw_data/SB/20220610_CR800Series_FogTable_SB.dat", skip = 1, stringsAsFactors = TRUE)
#Take out the first two rows
spicyraw6_10<- data2[-c(1,2), ]
#set timestamp as date
spicyraw6_10$TIMESTAMP<- as.POSIXct(spicyraw6_10$TIMESTAMP, tz="", format = "%Y-%m-%d %H:%M")

#joins datasets
spicy_ultimate<- full_join(spicyraw6_13,spicyraw6_10)
View(spicy_ultimate)

#Save processed Raw to processed folder
write.csv(spicy_ultimate, row.names = FALSE, file = "./processed_data/SB/SB_Processed.csv")
```

```{r}
batteryplot<- ggplot(spicyraw, aes(x=TIMESTAMP, y=BattV_Avg))+
  geom_point() + 
batteryplot

lwsinitial<- ggplot(spicyraw, aes(x=TIMESTAMP, y= LWmV_17ft_Avg))+
  geom_point() + 
  
lwsinitial

spicyraw2 <- spicyraw %>%
  mutate(day = date(TIMESTAMP),
         leaf = as.numeric(LWmV_17ft_Avg),
         hour = hour(TIMESTAMP))

spicyraw2$day <- as.factor(spicyraw2$day)

days <- unique(spicyraw2$day)

for(i in length(days)) {
  
  daydata <- filter(spicyraw2$day == days[i])
  
  ggplot(data = daydata,
         mapping = aes(x = hour,
                       y = LWmV_17ft_Avg))
  ggsave(filename = paste0('plotday', days[i], '.png'))
}

lapply(days, ggsave(ggplot(...)))

ggplot(data = spicyraw2,
       aes(x = hour, y = LWmV_17ft_Avg, color = day)) + 
  geom_point() +
  scale_y_discrete(breaks = seq(200, 1000, 100)) + 
  facet_wrap(~day) + 
  theme(axis.text.x = element_text(angle = 90))

View(spicyraw2)



spicyraw3 <- pivot_longer(spicyraw2, BattV_Avg:LWMWet_66ft_Tot,  names_to = 'data_type', values_to = 'value')

ggplot(data = spicyraw3,
       mapping = aes(x = TIMESTAMP, y = value)) + 
  geom_point() + 
  facet_wrap(~data_type)



spicyraw4 <- spicyraw2 %>%
  select(AirT_C_Avg,AirT_C_Std, TIMESTAMP) %>%
  ggplot(., 
         mapping = aes(x = TIMESTAMP, y = AirT_C_Avg)) + 
  geom_point()+
  geom_errorbar()

ggplot(data = filter(sst, year %in% tenyrs), 
       mapping = aes(x = year, y = surface_mean)) + 
  geom_linerange(mapping = aes(x = year, 
                               ymin = (surface_mean - surface_SD),
                               ymax = (surface_mean + surface_SD)),
                 color = 'gray70', size = 1) +
  geom_point(size = 2, color = '#440154FF') 

```

